#pragma once

#include "BaseDeclarations.h"
struct FViewUniformShaderParameters
{
	char __padding[0x900L];
	FMatrix& TranslatedWorldToClipField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.TranslatedWorldToClip"); }
	FMatrix& WorldToClipField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.WorldToClip"); }
	FMatrix& TranslatedWorldToViewField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.TranslatedWorldToView"); }
	FMatrix& ViewToTranslatedWorldField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.ViewToTranslatedWorld"); }
	FMatrix& ViewToClipField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.ViewToClip"); }
	FMatrix& ClipToViewField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.ClipToView"); }
	FMatrix& ClipToTranslatedWorldField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.ClipToTranslatedWorld"); }
	FMatrix& ScreenToWorldField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.ScreenToWorld"); }
	FMatrix& ScreenToTranslatedWorldField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.ScreenToTranslatedWorld"); }
	FVector& ViewForwardField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.ViewForward"); }
	FVector& ViewUpField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.ViewUp"); }
	FVector& ViewRightField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.ViewRight"); }
	FVector4& InvDeviceZToWorldZTransformField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.InvDeviceZToWorldZTransform"); }
	FVector4& ScreenPositionScaleBiasField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.ScreenPositionScaleBias"); }
	FVector4& ViewRectMinField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.ViewRectMin"); }
	FVector4& ViewSizeAndSceneTexelSizeField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.ViewSizeAndSceneTexelSize"); }
	FVector4& ViewOriginField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.ViewOrigin"); }
	FVector4& TranslatedViewOriginField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.TranslatedViewOrigin"); }
	FVector4& ExposureScaleField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.ExposureScale"); }
	FVector4& DiffuseOverrideParameterField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.DiffuseOverrideParameter"); }
	FVector4& SpecularOverrideParameterField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.SpecularOverrideParameter"); }
	FVector4& NormalOverrideParameterField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.NormalOverrideParameter"); }
	FVector2D& RoughnessOverrideParameterField() { return *GetNativePointerField<FVector2D*>(this, "FViewUniformShaderParameters.RoughnessOverrideParameter"); }
	FVector& PreViewTranslationField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.PreViewTranslation"); }
	float& OutOfBoundsMaskField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.OutOfBoundsMask"); }
	FVector& ViewOriginDeltaField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.ViewOriginDelta"); }
	float& CullingSignField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.CullingSign"); }
	float& NearPlaneField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.NearPlane"); }
	float& AdaptiveTessellationFactorField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AdaptiveTessellationFactor"); }
	float& GameTimeField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.GameTime"); }
	float& RealTimeField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.RealTime"); }
	unsigned int& RandomField() { return *GetNativePointerField<unsigned int*>(this, "FViewUniformShaderParameters.Random"); }
	unsigned int& FrameNumberField() { return *GetNativePointerField<unsigned int*>(this, "FViewUniformShaderParameters.FrameNumber"); }
	float& CameraCutField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.CameraCut"); }
	float& UseLightmapsField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.UseLightmaps"); }
	float& UnlitViewmodeMaskField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.UnlitViewmodeMask"); }
	FLinearColor& DirectionalLightColorField() { return *GetNativePointerField<FLinearColor*>(this, "FViewUniformShaderParameters.DirectionalLightColor"); }
	FVector& DirectionalLightDirectionField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.DirectionalLightDirection"); }
	float& DirectionalLightShadowTransitionField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.DirectionalLightShadowTransition"); }
	FVector4& DirectionalLightShadowSizeField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.DirectionalLightShadowSize"); }
	TStaticArray<FMatrix,2,16>& DirectionalLightScreenToShadowField() { return *GetNativePointerField<TStaticArray<FMatrix,2,16>*>(this, "FViewUniformShaderParameters.DirectionalLightScreenToShadow"); }
	FVector4& DirectionalLightShadowDistancesField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.DirectionalLightShadowDistances"); }
	FLinearColor& UpperSkyColorField() { return *GetNativePointerField<FLinearColor*>(this, "FViewUniformShaderParameters.UpperSkyColor"); }
	FLinearColor& LowerSkyColorField() { return *GetNativePointerField<FLinearColor*>(this, "FViewUniformShaderParameters.LowerSkyColor"); }
	TStaticArray<FVector4,2,16>& TranslucencyLightingVolumeMinField() { return *GetNativePointerField<TStaticArray<FVector4,2,16>*>(this, "FViewUniformShaderParameters.TranslucencyLightingVolumeMin"); }
	TStaticArray<FVector4,2,16>& TranslucencyLightingVolumeInvSizeField() { return *GetNativePointerField<TStaticArray<FVector4,2,16>*>(this, "FViewUniformShaderParameters.TranslucencyLightingVolumeInvSize"); }
	FVector4& TemporalAAParamsField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.TemporalAAParams"); }
	float& DepthOfFieldFocalDistanceField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.DepthOfFieldFocalDistance"); }
	float& DepthOfFieldScaleField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.DepthOfFieldScale"); }
	float& DepthOfFieldFocalLengthField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.DepthOfFieldFocalLength"); }
	float& DepthOfFieldFocalRegionField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.DepthOfFieldFocalRegion"); }
	float& DepthOfFieldNearTransitionRegionField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.DepthOfFieldNearTransitionRegion"); }
	float& DepthOfFieldFarTransitionRegionField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.DepthOfFieldFarTransitionRegion"); }
	float& MotionBlurNormalizedToPixelField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.MotionBlurNormalizedToPixel"); }
	float& GeneralPurposeTweakField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.GeneralPurposeTweak"); }
	float& DemosaicVposOffsetField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.DemosaicVposOffset"); }
	FMatrix& PrevProjectionField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.PrevProjection"); }
	FMatrix& PrevViewProjField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.PrevViewProj"); }
	FMatrix& PrevViewRotationProjField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.PrevViewRotationProj"); }
	FMatrix& PrevTranslatedWorldToClipField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.PrevTranslatedWorldToClip"); }
	FVector& PrevViewOriginField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.PrevViewOrigin"); }
	FVector& PrevPreViewTranslationField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.PrevPreViewTranslation"); }
	FMatrix& PrevInvViewProjField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.PrevInvViewProj"); }
	FMatrix& PrevScreenToTranslatedWorldField() { return *GetNativePointerField<FMatrix*>(this, "FViewUniformShaderParameters.PrevScreenToTranslatedWorld"); }
	FVector& IndirectLightingColorScaleField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.IndirectLightingColorScale"); }
	float& HdrMosaicField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.HdrMosaic"); }
	FVector& AtmosphericFogSunDirectionField() { return *GetNativePointerField<FVector*>(this, "FViewUniformShaderParameters.AtmosphericFogSunDirection"); }
	float& AtmosphericFogSunPowerField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogSunPower"); }
	float& AtmosphericFogPowerField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogPower"); }
	float& AtmosphericFogDensityScaleField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogDensityScale"); }
	float& AtmosphericFogDensityOffsetField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogDensityOffset"); }
	float& AtmosphericFogGroundOffsetField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogGroundOffset"); }
	float& AtmosphericFogDistanceScaleField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogDistanceScale"); }
	float& AtmosphericFogSkyInscatterScaleField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogSkyInscatterScale"); }
	float& AtmosphericFogAltitudeScaleField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogAltitudeScale"); }
	float& AtmosphericFogHeightScaleRayleighField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogHeightScaleRayleigh"); }
	float& AtmosphericFogStartDistanceField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogStartDistance"); }
	float& AtmosphericFogDistanceOffsetField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogDistanceOffset"); }
	float& AtmosphericFogSunDiscScaleField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AtmosphericFogSunDiscScale"); }
	unsigned int& AtmosphericFogRenderMaskField() { return *GetNativePointerField<unsigned int*>(this, "FViewUniformShaderParameters.AtmosphericFogRenderMask"); }
	unsigned int& AtmosphericFogInscatterAltitudeSampleNumField() { return *GetNativePointerField<unsigned int*>(this, "FViewUniformShaderParameters.AtmosphericFogInscatterAltitudeSampleNum"); }
	FLinearColor& AtmosphericFogSunColorField() { return *GetNativePointerField<FLinearColor*>(this, "FViewUniformShaderParameters.AtmosphericFogSunColor"); }
	FLinearColor& AmbientCubemapTintField() { return *GetNativePointerField<FLinearColor*>(this, "FViewUniformShaderParameters.AmbientCubemapTint"); }
	float& AmbientCubemapIntensityField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.AmbientCubemapIntensity"); }
	FVector2D& RenderTargetSizeField() { return *GetNativePointerField<FVector2D*>(this, "FViewUniformShaderParameters.RenderTargetSize"); }
	float& SkyLightParametersField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.SkyLightParameters"); }
	FVector4& SceneTextureMinMaxField() { return *GetNativePointerField<FVector4*>(this, "FViewUniformShaderParameters.SceneTextureMinMax"); }
	FLinearColor& SkyLightColorField() { return *GetNativePointerField<FLinearColor*>(this, "FViewUniformShaderParameters.SkyLightColor"); }
	TStaticArray<FVector4,7,16>& SkyIrradianceEnvironmentMapField() { return *GetNativePointerField<TStaticArray<FVector4,7,16>*>(this, "FViewUniformShaderParameters.SkyIrradianceEnvironmentMap"); }
	TStaticArray<FVector4,7,16>& SkyIrradianceEnvironmentMap1Field() { return *GetNativePointerField<TStaticArray<FVector4,7,16>*>(this, "FViewUniformShaderParameters.SkyIrradianceEnvironmentMap1"); }
	float& CapturesBlendWeightField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.CapturesBlendWeight"); }
	float& InvDisplayGammaField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.InvDisplayGamma"); }
	float& ES2PreviewModeField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.ES2PreviewMode"); }
	TStaticArray<FVector4,4,16>& GlobalVolumeCenterAndExtent_UBField() { return *GetNativePointerField<TStaticArray<FVector4,4,16>*>(this, "FViewUniformShaderParameters.GlobalVolumeCenterAndExtent_UB"); }
	TStaticArray<FVector4,4,16>& GlobalVolumeWorldToUVAddAndMul_UBField() { return *GetNativePointerField<TStaticArray<FVector4,4,16>*>(this, "FViewUniformShaderParameters.GlobalVolumeWorldToUVAddAndMul_UB"); }
	float& GlobalVolumeDimension_UBField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.GlobalVolumeDimension_UB"); }
	float& GlobalVolumeTexelSize_UBField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.GlobalVolumeTexelSize_UB"); }
	float& MaxGlobalDistance_UBField() { return *GetNativePointerField<float*>(this, "FViewUniformShaderParameters.MaxGlobalDistance_UB"); }

	// Functions

	static TArray<FUniformBufferStruct::FMember> * zzGetMembers(TArray<FUniformBufferStruct::FMember> * result) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *>(nullptr, "FViewUniformShaderParameters.zzGetMembers", result); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAdaptiveTessellationFactor __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAdaptiveTessellationFactor>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAmbientCubemapIntensity __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAmbientCubemapIntensity>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAmbientCubemapTint __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAmbientCubemapTint>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogAltitudeScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogAltitudeScale>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogDensityOffset __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogDensityOffset>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogDensityScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogDensityScale>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogDistanceOffset __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogDistanceOffset>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogDistanceScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogDistanceScale>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogGroundOffset __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogGroundOffset>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogHeightScaleRayleigh __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogHeightScaleRayleigh>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogInscatterAltitudeSampleNum __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogInscatterAltitudeSampleNum>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogPower __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogPower>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogRenderMask __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogRenderMask>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSkyInscatterScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSkyInscatterScale>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogStartDistance __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogStartDistance>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSunColor __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSunColor>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSunDirection __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSunDirection>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSunDiscScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSunDiscScale>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSunPower __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdAtmosphericFogSunPower>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdCameraCut __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdCameraCut>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdCapturesBlendWeight __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdCapturesBlendWeight>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdClipToTranslatedWorld __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdClipToTranslatedWorld>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdClipToView __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdClipToView>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdCullingSign __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdCullingSign>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDemosaicVposOffset __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDemosaicVposOffset>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldFarTransitionRegion __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldFarTransitionRegion>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldFocalDistance __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldFocalDistance>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldFocalLength __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldFocalLength>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldFocalRegion __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldFocalRegion>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldNearTransitionRegion __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldNearTransitionRegion>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDepthOfFieldScale>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDiffuseOverrideParameter __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDiffuseOverrideParameter>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightColor __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightColor>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightDirection __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightDirection>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightScreenToShadow __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightScreenToShadow>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowDistances __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowDistances>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowSampler __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowSampler>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowSize __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowSize>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowTexture __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowTexture>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowTransition __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdDirectionalLightShadowTransition>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdES2PreviewMode __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdES2PreviewMode>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdExposureScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdExposureScale>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdFrameNumber __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdFrameNumber>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGameTime __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGameTime>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGeneralPurposeTweak __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGeneralPurposeTweak>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldSampler0_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldSampler0_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldSampler1_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldSampler1_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldSampler2_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldSampler2_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldSampler3_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldSampler3_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldTexture0_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldTexture0_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldTexture1_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldTexture1_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldTexture2_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldTexture2_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldTexture3_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalDistanceFieldTexture3_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalVolumeCenterAndExtent_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalVolumeCenterAndExtent_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalVolumeDimension_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalVolumeDimension_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalVolumeTexelSize_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalVolumeTexelSize_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdGlobalVolumeWorldToUVAddAndMul_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdGlobalVolumeWorldToUVAddAndMul_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdHdrMosaic __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdHdrMosaic>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdIndirectLightingColorScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdIndirectLightingColorScale>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdInvDeviceZToWorldZTransform __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdInvDeviceZToWorldZTransform>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdInvDisplayGamma __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdInvDisplayGamma>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdLowerSkyColor __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdLowerSkyColor>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdMaxGlobalDistance_UB __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdMaxGlobalDistance_UB>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdMotionBlurNormalizedToPixel __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdMotionBlurNormalizedToPixel>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdNearPlane __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdNearPlane>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdNormalOverrideParameter __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdNormalOverrideParameter>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdOutOfBoundsMask __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdOutOfBoundsMask>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPreViewTranslation __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPreViewTranslation>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPrevInvViewProj __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPrevInvViewProj>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPrevPreViewTranslation __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPrevPreViewTranslation>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPrevProjection __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPrevProjection>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPrevScreenToTranslatedWorld __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPrevScreenToTranslatedWorld>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPrevTranslatedWorldToClip __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPrevTranslatedWorldToClip>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPrevViewOrigin __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPrevViewOrigin>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPrevViewProj __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPrevViewProj>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdPrevViewRotationProj __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdPrevViewRotationProj>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdRandom __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdRandom>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdRealTime __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdRealTime>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdRenderTargetSize __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdRenderTargetSize>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdRoughnessOverrideParameter __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdRoughnessOverrideParameter>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdSceneTextureMinMax __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdSceneTextureMinMax>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdScreenPositionScaleBias __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdScreenPositionScaleBias>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdScreenToTranslatedWorld __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdScreenToTranslatedWorld>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdScreenToWorld __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdScreenToWorld>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdSkyIrradianceEnvironmentMap1 __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdSkyIrradianceEnvironmentMap1>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdSkyIrradianceEnvironmentMap __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdSkyIrradianceEnvironmentMap>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdSkyLightColor __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdSkyLightColor>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdSkyLightParameters __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdSkyLightParameters>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdSpecularOverrideParameter __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdSpecularOverrideParameter>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdTemporalAAParams __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdTemporalAAParams>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdTranslatedViewOrigin __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdTranslatedViewOrigin>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdTranslatedWorldToClip __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdTranslatedWorldToClip>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdTranslatedWorldToView __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdTranslatedWorldToView>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdTranslucencyLightingVolumeInvSize __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdTranslucencyLightingVolumeInvSize>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdTranslucencyLightingVolumeMin __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdTranslucencyLightingVolumeMin>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdUnlitViewmodeMask __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdUnlitViewmodeMask>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdUpperSkyColor __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdUpperSkyColor>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdUseLightmaps __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdUseLightmaps>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewForward __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewForward>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewOrigin __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewOrigin>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewOriginDelta __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewOriginDelta>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewRectMin __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewRectMin>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewRight __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewRight>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewSizeAndSceneTexelSize __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewSizeAndSceneTexelSize>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewToClip __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewToClip>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewToTranslatedWorld __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewToTranslatedWorld>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdViewUp __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdViewUp>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FViewUniformShaderParameters::zzNextMemberIdWorldToClip __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FViewUniformShaderParameters::zzNextMemberIdWorldToClip>(nullptr, "FViewUniformShaderParameters.zzGetMembersBefore", result, __formal); }
};

