#pragma once

#include "BaseDeclarations.h"
#include "UObject.h"
#include "UObjectBaseUtility.h"
#include "UObjectBase.h"

struct USCS_Node : UObject
{
	char __padding[0x70L];
	FName& VariableNameField() { return *GetNativePointerField<FName*>(this, "USCS_Node.VariableName"); }
	FName& CategoryNameField() { return *GetNativePointerField<FName*>(this, "USCS_Node.CategoryName"); }
	FName& AttachToNameField() { return *GetNativePointerField<FName*>(this, "USCS_Node.AttachToName"); }
	FName& ParentComponentOrVariableNameField() { return *GetNativePointerField<FName*>(this, "USCS_Node.ParentComponentOrVariableName"); }
	FName& ParentComponentOwnerClassNameField() { return *GetNativePointerField<FName*>(this, "USCS_Node.ParentComponentOwnerClassName"); }
	bool& bIsParentComponentNativeField() { return *GetNativePointerField<bool*>(this, "USCS_Node.bIsParentComponentNative"); }
	TArray<USCS_Node *>& ChildNodesField() { return *GetNativePointerField<TArray<USCS_Node *>*>(this, "USCS_Node.ChildNodes"); }
	TArray<FBPVariableMetaDataEntry>& MetaDataArrayField() { return *GetNativePointerField<TArray<FBPVariableMetaDataEntry>*>(this, "USCS_Node.MetaDataArray"); }
	bool& bIsFalseRoot_DEPRECATEDField() { return *GetNativePointerField<bool*>(this, "USCS_Node.bIsFalseRoot_DEPRECATED"); }
	bool& bIsNative_DEPRECATEDField() { return *GetNativePointerField<bool*>(this, "USCS_Node.bIsNative_DEPRECATED"); }
	FName& NativeComponentName_DEPRECATEDField() { return *GetNativePointerField<FName*>(this, "USCS_Node.NativeComponentName_DEPRECATED"); }
	bool& bVariableNameAutoGenerated_DEPRECATEDField() { return *GetNativePointerField<bool*>(this, "USCS_Node.bVariableNameAutoGenerated_DEPRECATED"); }

	// Functions

	void ExecuteNodeOnActor(AActor * Actor, USceneComponent * ParentComponent, const FTransform * RootTransform, bool bIsDefaultTransform) { NativeCall<void, AActor *, USceneComponent *, const FTransform *, bool>(this, "USCS_Node.ExecuteNodeOnActor", Actor, ParentComponent, RootTransform, bIsDefaultTransform); }
	TArray<USCS_Node *> * GetAllNodes(TArray<USCS_Node *> * result) { return NativeCall<TArray<USCS_Node *> *, TArray<USCS_Node *> *>(this, "USCS_Node.GetAllNodes", result); }
	FName * GetVariableName(FName * result) { return NativeCall<FName *, FName *>(this, "USCS_Node.GetVariableName", result); }
};

