#pragma once

#include "BaseDeclarations.h"
struct FGPUSpriteEmitterUniformParameters
{
	char __padding[0xb0L];
	FVector4& ColorCurveField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.ColorCurve"); }
	FVector4& ColorScaleField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.ColorScale"); }
	FVector4& ColorBiasField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.ColorBias"); }
	FVector4& MiscCurveField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.MiscCurve"); }
	FVector4& MiscScaleField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.MiscScale"); }
	FVector4& MiscBiasField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.MiscBias"); }
	FVector4& SizeBySpeedField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.SizeBySpeed"); }
	FVector4& SubImageSizeField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.SubImageSize"); }
	FVector4& TangentSelectorField() { return *GetNativePointerField<FVector4*>(this, "FGPUSpriteEmitterUniformParameters.TangentSelector"); }
	float& RotationRateScaleField() { return *GetNativePointerField<float*>(this, "FGPUSpriteEmitterUniformParameters.RotationRateScale"); }
	float& RotationBiasField() { return *GetNativePointerField<float*>(this, "FGPUSpriteEmitterUniformParameters.RotationBias"); }
	float& CameraMotionBlurAmountField() { return *GetNativePointerField<float*>(this, "FGPUSpriteEmitterUniformParameters.CameraMotionBlurAmount"); }
	FVector2D& PivotOffsetField() { return *GetNativePointerField<FVector2D*>(this, "FGPUSpriteEmitterUniformParameters.PivotOffset"); }

	// Functions

	static TArray<FUniformBufferStruct::FMember> * zzGetMembers(TArray<FUniformBufferStruct::FMember> * result) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembers", result); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdCameraMotionBlurAmount __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdCameraMotionBlurAmount>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdColorBias __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdColorBias>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdColorCurve __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdColorCurve>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdColorScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdColorScale>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdMiscBias __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdMiscBias>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdMiscCurve __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdMiscCurve>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdMiscScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdMiscScale>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdPivotOffset __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdPivotOffset>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdRotationBias __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdRotationBias>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdRotationRateScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdRotationRateScale>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdSizeBySpeed __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdSizeBySpeed>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdSubImageSize __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdSubImageSize>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FGPUSpriteEmitterUniformParameters::zzNextMemberIdTangentSelector __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FGPUSpriteEmitterUniformParameters::zzNextMemberIdTangentSelector>(nullptr, "FGPUSpriteEmitterUniformParameters.zzGetMembersBefore", result, __formal); }
};

