#pragma once

#include "BaseDeclarations.h"
struct FPrimitiveUniformShaderParameters
{
	char __padding[0x110L];
	FMatrix& LocalToWorldField() { return *GetNativePointerField<FMatrix*>(this, "FPrimitiveUniformShaderParameters.LocalToWorld"); }
	FMatrix& WorldToLocalField() { return *GetNativePointerField<FMatrix*>(this, "FPrimitiveUniformShaderParameters.WorldToLocal"); }
	FVector4& ObjectWorldPositionAndRadiusField() { return *GetNativePointerField<FVector4*>(this, "FPrimitiveUniformShaderParameters.ObjectWorldPositionAndRadius"); }
	FVector& ObjectBoundsField() { return *GetNativePointerField<FVector*>(this, "FPrimitiveUniformShaderParameters.ObjectBounds"); }
	float& LocalToWorldDeterminantSignField() { return *GetNativePointerField<float*>(this, "FPrimitiveUniformShaderParameters.LocalToWorldDeterminantSign"); }
	FVector& ActorWorldPositionField() { return *GetNativePointerField<FVector*>(this, "FPrimitiveUniformShaderParameters.ActorWorldPosition"); }
	float& DecalReceiverMaskField() { return *GetNativePointerField<float*>(this, "FPrimitiveUniformShaderParameters.DecalReceiverMask"); }
	float& HasDistanceFieldRepresentationField() { return *GetNativePointerField<float*>(this, "FPrimitiveUniformShaderParameters.HasDistanceFieldRepresentation"); }
	float& HasHeightfieldRepresentationField() { return *GetNativePointerField<float*>(this, "FPrimitiveUniformShaderParameters.HasHeightfieldRepresentation"); }
	float& UseEditorDepthTestField() { return *GetNativePointerField<float*>(this, "FPrimitiveUniformShaderParameters.UseEditorDepthTest"); }
	FVector4& ObjectOrientationField() { return *GetNativePointerField<FVector4*>(this, "FPrimitiveUniformShaderParameters.ObjectOrientation"); }
	FVector4& NonUniformScaleField() { return *GetNativePointerField<FVector4*>(this, "FPrimitiveUniformShaderParameters.NonUniformScale"); }
	FVector4& InvNonUniformScaleField() { return *GetNativePointerField<FVector4*>(this, "FPrimitiveUniformShaderParameters.InvNonUniformScale"); }
	FVector& LocalObjectBoundsMinField() { return *GetNativePointerField<FVector*>(this, "FPrimitiveUniformShaderParameters.LocalObjectBoundsMin"); }
	FVector& LocalObjectBoundsMaxField() { return *GetNativePointerField<FVector*>(this, "FPrimitiveUniformShaderParameters.LocalObjectBoundsMax"); }
	float& LpvBiasMultiplierField() { return *GetNativePointerField<float*>(this, "FPrimitiveUniformShaderParameters.LpvBiasMultiplier"); }

	// Functions

	static TArray<FUniformBufferStruct::FMember> * zzGetMembers(TArray<FUniformBufferStruct::FMember> * result) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembers", result); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdActorWorldPosition __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdActorWorldPosition>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdDecalReceiverMask __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdDecalReceiverMask>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdHasDistanceFieldRepresentation __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdHasDistanceFieldRepresentation>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdHasHeightfieldRepresentation __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdHasHeightfieldRepresentation>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdInvNonUniformScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdInvNonUniformScale>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdLocalObjectBoundsMax __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdLocalObjectBoundsMax>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdLocalObjectBoundsMin __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdLocalObjectBoundsMin>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdLocalToWorld __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdLocalToWorld>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdLocalToWorldDeterminantSign __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdLocalToWorldDeterminantSign>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdLpvBiasMultiplier __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdLpvBiasMultiplier>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdNonUniformScale __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdNonUniformScale>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdObjectBounds __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdObjectBounds>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdObjectOrientation __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdObjectOrientation>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdObjectWorldPositionAndRadius __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdObjectWorldPositionAndRadius>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdUseEditorDepthTest __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdUseEditorDepthTest>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
	static TArray<FUniformBufferStruct::FMember> * zzGetMembersBefore(TArray<FUniformBufferStruct::FMember> * result, FPrimitiveUniformShaderParameters::zzNextMemberIdWorldToLocal __formal) { return NativeCall<TArray<FUniformBufferStruct::FMember> *, TArray<FUniformBufferStruct::FMember> *, FPrimitiveUniformShaderParameters::zzNextMemberIdWorldToLocal>(nullptr, "FPrimitiveUniformShaderParameters.zzGetMembersBefore", result, __formal); }
};

